version: "3.9"

# Названия сервисов
services:
  serv_postgres:
    image: postgres:16
    container_name: yt_postgres
    volumes:
      - ~/.pg/pg_data/yt:/var/lib/postgresql/data
    env_file:
      - .env
  django_project:
    build:
     dockerfile: ./Dockerfile
     context: .
    container_name: yt_django
    depends_on:
      - serv_postgres
    volumes:
      - static_volume:/yt/staticfiles
      - media_volume:/yt/media
    environment:
      - POSTGRES_HOST=serv_postgres
    env_file:
      - .env
    command: >
      bash -c "sleep 20 && python manage.py collectstatic --noinput && python manage.py migrate && gunicorn -b 0.0.0.0:8000 my_store.wsgi:application"
  nginx:
    build:
      dockerfile: ./Dockerfile
      context: ./nginx/
    container_name: yt_nginx
    image: yt_nginx
    volumes:
      - static_volume:/yt/staticfiles
      - media_volume:/yt/media
    depends_on:
      - django_project
    ports:
      - "${NGINX_EXTERNAL_PORT}:80"

volumes:
  static_volume:
  media_volume:
